[workspace]
members = [
    "apps/bevy/invaders",
    "libs/tdd/adder",
    "apps/guessing-game",
    "apps/hello-world",
    "libs/rust-lib",
    "apps/rust-app",
    "apps/hello-cargo",
]
resolver = "2" # "2" is the default resolver ! Important! wpu/Bevy needs this!