[package]
name = "greeta"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
bevy = "0.7.0"
bevy_egui = "0.14"
bevy-inspector-egui = "0.11.0"